# Generated by Django 5.2.1 on 2025-06-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_alter_listing_provider_delete_rentalprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
