# Generated by Django 5.2.1 on 2025-06-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bikestation_carstation_homestay_bike_car_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bike')),
                ('bike_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bikestation')),
            ],
        ),
        migrations.CreateModel(
            name='BookingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('car_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carstation')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHomestay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homestay')),
            ],
        ),
    ]
