# Generated by Django 5.2.1 on 2025-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_stations/'),
        ),
        migrations.AddField(
            model_name='carstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_stations/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
