# Generated by Django 5.2.1 on 2025-06-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bikestation_image_carstation_image_room_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghomestay',
            name='homestay',
        ),
        migrations.AddField(
            model_name='bookinghomestay',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AddField(
            model_name='bookinghomestay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homestays/'),
        ),
    ]
