# Generated by Django 5.2.1 on 2025-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bookingbike_user_bookingcar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghomestay',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingbike',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingcar',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
    ]
