# Generated by Django 5.2.1 on 2025-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
