# Generated by Django 5.2.1 on 2025-07-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_serviceprovider_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
            preserve_default=False,
        ),
    ]
