# Generated by Django 5.2.1 on 2025-07-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bike_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carstation',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestay',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
            preserve_default=False,
        ),
    ]
