# Generated by Django 5.2.1 on 2025-07-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bikestation_service_provider_car_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='booking_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookingbike'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='booking_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookingcar'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='booking_homestay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookinghomestay'),
        ),
    ]
