# Generated by Django 5.2.1 on 2025-07-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userfeedback_booking_bike_userfeedback_booking_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
        ),
    ]
