# Generated by Django 5.2.1 on 2025-07-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userfeedback_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='booking_bike',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='booking_car',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='booking_homestay',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='bike_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bikestation'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='car_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carstation'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='homestay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.homestay'),
        ),
    ]
