from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/choose/', views.choose_registration, name='choose_registration'),
    path('register/', views.register, name='register'),
    path('provider/register/', views.service_provider_register, name='service_provider_register'),
    path('pending-providers/', views.pending_providers, name='pending_providers'),
    path('post-login/', views.post_login_redirect, name='post_login_redirect'),
    path('waiting-approval/', views.waiting_for_approval, name='waiting_for_approval'),
    path('approve-provider/<int:provider_id>/', views.approve_provider, name='approve_provider'),
    path('reject-provider/<int:provider_id>/', views.reject_provider, name='reject_provider'),
    path('provider-dashboard/', views.provider_dashboard, name='provider_dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('customer_dashboard/', views.customer_dashboard, name='customer_dashboard'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('admin/home/', views.admin_home, name='admin_home'),
    path('provider/profile/edit/', views.edit_service_provider_profile, name='edit_service_provider_profile'),
    path('customer/profile/edit/', views.edit_customer_profile, name='edit_customer_profile'),
    path('custom-admin/reports/', views.admin_reports, name='admin_reports'),
    
    path('provider/add-bike/', views.provider_add_bike, name='provider_add_bike'),
    path('provider/add-bike-station/', views.provider_add_bike_station, name='provider_add_bike_station'),
    path('provider/add-car/', views.provider_add_car, name='provider_add_car'),
    path('provider/add-car-station/', views.provider_add_car_station, name='provider_add_car_station'),
    path('provider/add-room/', views.provider_add_room, name='provider_add_room'),
    path('provider/add-homestay/', views.provider_add_homestay, name='provider_add_homestay'),
    path('provider/manage-resource/', views.provider_manage_resource, name='provider_manage_resource'),
    path('provider/edit-bike/<int:bike_id>/', views.provider_edit_bike, name='provider_edit_bike'),
    path('provider/delete-bike/<int:bike_id>/', views.provider_delete_bike, name='provider_delete_bike'),
    path('provider/edit-bike-station/<int:station_id>/', views.provider_edit_bike_station, name='provider_edit_bike_station'),
    path('provider/delete-bike-station/<int:station_id>/', views.provider_delete_bike_station, name='provider_delete_bike_station'),
    path('provider/edit-car/<int:car_id>/', views.provider_edit_car, name='provider_edit_car'),
    path('provider/delete-car/<int:car_id>/', views.provider_delete_car, name='provider_delete_car'),
    path('provider/edit-car-station/<int:station_id>/', views.provider_edit_car_station, name='provider_edit_car_station'),
    path('provider/delete-car-station/<int:station_id>/', views.provider_delete_car_station, name='provider_delete_car_station'),
    path('provider/edit-room/<int:room_id>/', views.provider_edit_room, name='provider_edit_room'),
    path('provider/delete-room/<int:room_id>/', views.provider_delete_room, name='provider_delete_room'),
    path('provider/edit-homestay/<int:homestay_id>/', views.provider_edit_homestay, name='provider_edit_homestay'),
    path('provider/delete-homestay/<int:homestay_id>/', views.provider_delete_homestay, name='provider_delete_homestay'),
    path('provider/manage-booking/', views.provider_manage_booking, name='provider_manage_booking'),
    path('provider/user-feedback/', views.provider_feedback, name='provider_user_feedback'),

    path('user-details/', views.user_details, name='user_details'),
    path('user-feedback/', views.user_feedback, name='user_feedback'),

    path('homestays/', views.homestay_list, name='homestay_list'),
    path('homestays/<int:homestay_id>/rooms/', views.homestay_rooms, name='homestay_rooms'),
    path('homestays/rooms/<int:room_id>/booking/', views.homestay_booking, name='homestay_booking'),
    path('homestays/booking/confirmation/', views.homestay_booking_confirmation, name='homestay_booking_confirmation'),
    path('homestays/booking/payment/', views.homestay_payment, name='homestay_payment'),
    path('booking/success/', views.booking_success, name='booking_success'),  
    path('bike-stations/', views.bike_station_list, name='bike_station_list'),
    path('bike-stations/', views.bike_station_list, name='bike_station_list'),
    path('bike-stations/<int:station_id>/bikes/', views.bike_list, name='bike_list'),
    path('rent-bike/<int:station_id>/<int:bike_id>/', views.rent_bike, name='rent_bike'),
    path('bike/booking/confirmation/', views.bike_booking_confirmation, name='bike_booking_confirmation'),
    path('bike/payment/', views.bike_payment, name='bike_payment_form'),
    path('booking-success/', views.booking_success, name='booking_success'),
    path('car-stations/', views.car_station_list, name='car_station_list'),
    path('car-stations/<int:station_id>/cars/', views.car_list, name='car_list'),
    path('rent-car/<int:station_id>/<int:car_id>/', views.rent_car, name='rent_car'),
    path('car/booking/confirmation/', views.car_booking_confirmation, name='car_booking_confirmation'),
    path('car/payment/', views.car_payment_form, name='car_payment_form'),
    path('booking-success/', views.booking_success, name='booking_success'),
    path('booking-history/', views.booking_history, name='booking_history'),
    path('feedback/', views.feedback, name='feedback'),
]
